## ROS2
FROM osrf/ros:humble-desktop-full

# Set up the workspace
WORKDIR /workspace
RUN mkdir -p src

RUN apt update -y
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/New_York
RUN apt install -y \
            software-properties-common \
            tree \
            vim \
            less \
            htop \
            wget \
            curl \
            zsh \
            git
RUN echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list
RUN wget https://packages.osrfoundation.org/gazebo.key -O - | apt-key add -
RUN apt update -y

RUN apt install gazebo libgazebo-dev -y
RUN apt install \
            ros-humble-gazebo-ros-pkgs \
            ros-humble-ros2-control \
            ros-humble-ros2-controllers \
            ros-humble-gazebo-ros2-control \
            ros-humble-xacro \
            ros-humble-joint-state-publisher \
            ros-humble-joint-state-publisher-gui \
            ros-humble-tf2-tools \
            ros-humble-tf-transformations \
            ros-humble-image-view \
            libcanberra-gtk3-module \
            python3-pip -y
RUN pip3 install opencv-python transforms3d setuptools==58.2.0

CMD ["bash"]
